version: "3.9"
services:

  telebot:
    build: 
      context: telegram_bot/
    env_file:
      - ./telegram_bot/.env
    depends_on:
      - engine
    #image: care1e55/telegram_bot:latest
    container_name: telegram_bot

  engine:
    #env_file: ./engine/.env
    build: 
      context: engine/ 
      args:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    restart: always
    expose: 
      - 5000
    # image: care1e55/engine:latest
    container_name: engine
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://engine:5000/api/ready"]
    #   #test: ["CMD", "curl", "-X", "GET", "-f", "http://localhost:5000/api/ready"]
    #   interval: 30s
    #   timeout: 5s
    #   retries: 10
