name: workflow
# on: push
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: deploy
    # environment: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push engine
        uses: docker/build-push-action@v2
        with:
          context: ./engine
          file: ./engine/Dockerfile
          push: true
          tags: care1e55/engine:latest
      - name: Build and push bot
        uses: docker/build-push-action@v2
        with:
          context: ./telegram_bot
          file: ./telegram_bot/Dockerfile
          push: true
          tags: care1e55/telegram_bot:latest
          build-args: |
            ENGINE_IP=localhost
            ENGINE_PORT=5000
            TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}
      - name: copy docker-compose via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVICE_HOST }}
          username: root
          password: ${{ secrets.SERVICE_PASSWORD }}
          port: 22
          source: "docker-compose.yaml"
          target: "/root/"
      - name: pull and run engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVICE_HOST }}
          username: root
          password: ${{ secrets.SERVICE_PASSWORD }}
          port: 22
          script: |
            docker rm -f engine telegram_bot
            docker rmi -f care1e55/engine care1e55/telegram_bot
            docker-compose pull
            docker-compose up --no-build -d
            sleep 30
            curl -X POST -H 'Content-type: application/json' --data '{"text":"привет всем, подскажите пожалуйста курсы по питону", "top_k": 3}' http://localhost:5000/api/get_messages