name: test workflow
on: push

jobs:
  test:
    name: test engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - run: ls -la .
      - run: docker build ./engine -t engine
      - run: docker build ./telegram_bot -t telegram_bot
