name: test workflow
on: push

jobs:
  test:
    name: test engine
    runs-on: ubuntu-latest
    steps:
      - run: docker build ../engine -t engine
      - run: docker run -p 5000:5000 -d engine
      - uses: wei/curl@master
        with:
          args: http://localhost:5000/api/get_messages
      