name: test workflow
on: push

jobs:
  test:
    name: test engine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1  
      - run: ls -la .
      - run: docker build ./engine -t engine
      - run: docker run -v $(pwd)/engine/data:/usr/src/app/data -v $(pwd)/engine/models/:/root/.cache/torch/sentence_transformers/ engine
      - run: sleep 300
      - run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"привет всем, подскажите пожалуйста курсы по питону", "top_k": 3}' http://localhost:5000/api/get_messages
      